# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 651a0634a6a7c891644a0c52b14d1a9f7d1d5046a898333eb8563eaf4c8a85618ade8619ac66835026c910a81842ca82090a7688662099a003f7121735f758c9

test:
  secret_key_base: 07c37ecf6a4750d254526e37039d984e2330f16812787c3c4da8b2dfa3f5b907b11dc23d9e6fba7425b703ae159517f7869b29f72a0cbb3be5279d2aab7c74fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
